@startuml
left to right direction
actor "autheur" as us
actor "user" as ad
rectangle BLOG {

  usecase "CRUD ARTICL" as UC1
  usecase "CRUD CATEGORY" as UC3
  usecase "CONSULTER ARTICL" as UC2

}
us -- UC1
us -- UC3
ad -- UC2


@enduml